### ISSUE TITLE
Error: No matching login attempt found

### ISSUE THREAD

**Issue by num3a** [PoBuchi/meteor-accounts-linkedin#20]
I get the following error using meteor-accounts-linkedin only on mobile, using a Android/ Google Chrome 54.
When Linkedin redirects me to my app, the app cannot login.

message: No matching login attempt found [145546287] 
stack:
Error: No matching login attempt found [145546287]
    at [object Object].<anonymous> (packages/accounts-oauth.js:113:21)
    at packages/accounts-base/accounts_server.js:471:32
    at tryLoginMethod (packages/accounts-base/accounts_server.js:248:14)
    at AccountsServer.Ap._runLoginHandlers (packages/accounts-base/accounts_server.js:468:18)
    at [object Object].methods.login (packages/accounts-base/accounts_server.js:531:27)
    at [object Object].methodMap.(anonymous function) (packages/meteorhacks_kadira.js:2731:30)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1712:12)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:709:40

https://ui.kadira.io/et/5cba73dd-bbd4-44c0-bff5-504eb116e2c4/qxeEaGEwHYCHvEMfP

**Comment by feruap** [comment]
Did you find a solution?
