### ISSUE TITLE
Unable to start meteor after pauli:accounts-linkedin

### ISSUE THREAD

**Issue by tpham045** [PoBuchi/meteor-accounts-linkedin#21]
Hi, I am just starting learning how to allow user login in my Meteor using LinkedIn credential and this package. Before adding the package, I still able to run 'meteor -p 8080'. After adding the package, I got the error below. I am not sure the package causing this error so that I tried remove it. It works fine again after removing. 

If you still actively working on this package, please assist. Appreciated.

**Version: Meteor 1.4.2.7.** 

**Error:**
After `meteor add pauli:accounts-linkedin`, I have this:
```
Changes to your project's package version selections:                                              
accounts-base            added, version 1.2.14
accounts-oauth           added, version 1.1.15
ddp-rate-limiter         added, version 1.0.6
localstorage             added, version 1.0.12
oauth                    added, version 1.1.12
oauth2                   added, version 1.1.11
pauli:accounts-linkedin  added, version 1.3.1
pauli:linkedin           added, version 1.3.1
rate-limit               added, version 1.0.6
service-configuration    added, version 1.0.11                                              
pauli:accounts-linkedin: Accounts service for LinkedIn accounts
```

Then I start the app (without adding any new code yet)

```
tpham045:~/workspace/portfolio (LinkedInAPI) $ meteor -p 8080
W20170215-21:40:47.566(0)? (STDERR)           
W20170215-21:40:47.698(0)? (STDERR) /home/ubuntu/.meteor/packages/meteor-tool/.1.4.2_6.uykbpj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:313
W20170215-21:40:47.699(0)? (STDERR)                                             throw(ex);
W20170215-21:40:47.699(0)? (STDERR)                                             ^
W20170215-21:40:47.708(0)? (STDERR) MongoError: not authorized on heroku_5x9b24w5 to execute command { insert: "system.indexes", documents: [ { ns: "heroku_5x9b24w5.users", key: { username: 1 }, name: "username_1", unique: 1, sparse: 1 } ], ordered: true }
W20170215-21:40:47.708(0)? (STDERR)     at Object.Future.wait (/home/ubuntu/.meteor/packages/meteor-tool/.1.4.2_6.uykbpj++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:449:15)
W20170215-21:40:47.709(0)? (STDERR)     at MongoConnection._ensureIndex (packages/mongo/mongo_driver.js:828:10)
W20170215-21:40:47.709(0)? (STDERR)     at [object Object].Mongo.Collection._ensureIndex (packages/mongo/collection.js:685:20)
W20170215-21:40:47.709(0)? (STDERR)     at setupUsersCollection (packages/accounts-base/accounts_server.js:1491:9)
W20170215-21:40:47.710(0)? (STDERR)     at new AccountsServer (packages/accounts-base/accounts_server.js:51:5)
W20170215-21:40:47.710(0)? (STDERR)     at meteorInstall.node_modules.meteor.accounts-base.server_main.js (packages/accounts-base/server_main.js:9:12)
W20170215-21:40:47.711(0)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:181:9)
W20170215-21:40:47.711(0)? (STDERR)     at require (packages/modules-runtime.js:106:16)
W20170215-21:40:47.712(0)? (STDERR)     at /home/ubuntu/workspace/portfolio/.meteor/local/build/programs/server/packages/accounts-base.js:1972:15
W20170215-21:40:47.713(0)? (STDERR)     at /home/ubuntu/workspace/portfolio/.meteor/local/build/programs/server/packages/accounts-base.js:1983:3
W20170215-21:40:47.713(0)? (STDERR)     - - - - -
W20170215-21:40:47.713(0)? (STDERR)     at Function.MongoError.create (/home/ubuntu/.meteor/packages/npm-mongo/.2.2.11_2.8w0uvr++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/error.js:31:11)
W20170215-21:40:47.714(0)? (STDERR)     at /home/ubuntu/.meteor/packages/npm-mongo/.2.2.11_2.8w0uvr++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:483:72
W20170215-21:40:47.714(0)? (STDERR)     at authenticateStragglers (/home/ubuntu/.meteor/packages/npm-mongo/.2.2.11_2.8w0uvr++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:429:16)
W20170215-21:40:47.714(0)? (STDERR)     at [object Object].messageHandler (/home/ubuntu/.meteor/packages/npm-mongo/.2.2.11_2.8w0uvr++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/pool.js:463:5)
W20170215-21:40:47.715(0)? (STDERR)     at Socket.<anonymous> (/home/ubuntu/.meteor/packages/npm-mongo/.2.2.11_2.8w0uvr++os+web.browser+web.cordova/npm/node_modules/mongodb-core/lib/connection/connection.js:309:22)
W20170215-21:40:47.715(0)? (STDERR)     at emitOne (events.js:77:13)
W20170215-21:40:47.716(0)? (STDERR)     at Socket.emit (events.js:169:7)
W20170215-21:40:47.716(0)? (STDERR)     at readableAddChunk (_stream_readable.js:153:18)
W20170215-21:40:47.716(0)? (STDERR)     at Socket.Readable.push (_stream_readable.js:111:10)
W20170215-21:40:47.717(0)? (STDERR)     at TCP.onread (net.js:537:20)
=> Exited with code: 1
```

**Comment by PoBuchi** [comment]
@tpham045 Will take a look tomorrow.

**Comment by PoBuchi** [comment]
started looking at it

**Comment by PoBuchi** [comment]
@tpham045 was that Mongo connection error?:)
