### ISSUE TITLE
Having difficulties using Meteor 1.6.1

### ISSUE THREAD

**Issue by carlosalvidrez** [PoBuchi/meteor-accounts-linkedin#27]
Hi! I installed the package and are now getting this error... used to work a while ago but I'm not sure which version of Meteor may have presented the issue first.

I get no error on the MEteor server console, but I do get this error on the Client side (other logins work... Facebook, Google, Twitter), so I wonder if there might be an incompatibility issue between Meteor 1.6.1, and your package.

Thanks by the way!

accounts-ui-unstyled.js:1245 Uncaught TypeError: loginWithService is not a function
    at Object.click .login-button (accounts-ui-unstyled.js:1245)
    at blaze.js:3775
    at Function.Template._withTemplateInstanceFunc (blaze.js:3744)
    at Blaze.View.<anonymous> (blaze.js:3774)
    at blaze.js:2617
    at Object.Blaze._withCurrentView (blaze.js:2271)
    at Blaze._DOMRange.<anonymous> (blaze.js:2616)
    at HTMLDivElement.<anonymous> (blaze.js:863)
    at HTMLDivElement.dispatch (jquery.js:4721)
    at HTMLDivElement.elemData.handle (jquery.js:4389)

**Comment by esgy** [comment]
Hey!
I also have issues with 1.6.1 but I get a different error:

```Error in OAuth Server: Failed to complete OAuth handshake with LinkedIn.Cannot read property 'post' of undefined
Exception while invoking method 'login' Error: Failed to complete  OAuth handshake withLinkedIn. Cannot read property 'post' of undefined
at getTokenResponse (packages/pauli:linkedin-oauth/linkedin-server.js:87:11)
at Object.handleOauthRequest (packages/pauli:linkedin-oauth/linkedin-server.js:5:18)
at OAuth._requestHandlers.(anonymous function) (packages/oauth2.js:27:31)
at middleware (packages/oauth.js:203:5)
at packages/oauth.js:176:5```

**Comment by PoBuchi** [comment]
back from holiday will take a look tomorrow

**Comment by ddaydd** [comment]
Hi,
Same, any news?
`
Exception while invoking method 'login' Error: Failed to complete  OAuth handshake withLinkedIn. Cannot read property 'post' of undefined..`

**Comment by esgy** [comment]
I updated to 3.0.0 and renamed `loginWithLinkedIn` to `loginWithLinkedin` and works for me.

**Comment by carlosalvidrez** [comment]
Not getting a client error now, but getting the following on the server:

W20180206-22:31:48.478(-5) (oauth.js:101) Unable to base64 decode state from OAuth query: undefined
W20180206-22:31:48.479(-5) (oauth.js:101) Unable to base64 decode state from OAuth query: undefined
W20180206-22:31:48.479(-5) (oauth.js:431) Error in OAuth Server: invalid_request

Just thought I'd mention it in case you already know how to solve for this... wondering what the base64 message means.

Thanks!
